# Example configuration for the Interpolation integration
# Add this to your Home Assistant configuration.yaml

sensor:
  # Example 1: Temperature correction based on calibration points
  - platform: interpolation
    name: "Corrected Temperature"
    source_entity: sensor.raw_temperature
    x_values: [0, 10, 20, 30, 40]
    y_values: [0.5, 10.2, 20.1, 30.3, 40.5]
    unit_of_measurement: "°C"
    unique_id: "corrected_temperature_01"

  # Example 2: Fan speed curve mapping
  - platform: interpolation
    name: "Fan Speed Curve"
    source_entity: input_number.fan_control
    x_values: [0, 25, 50, 75, 100]
    y_values: [0, 10, 30, 70, 100]
    unit_of_measurement: "%"
    unique_id: "fan_speed_curve_01"

  # Example 3: Battery voltage to percentage conversion
  - platform: interpolation
    name: "Battery Percentage"
    source_entity: sensor.battery_voltage
    x_values: [3.0, 3.3, 3.6, 3.9, 4.2]
    y_values: [0, 25, 50, 75, 100]
    unit_of_measurement: "%"
    unique_id: "battery_percentage_01"

  # Example 4: Light brightness mapping
  - platform: interpolation
    name: "Light Brightness Curve"
    source_entity: input_number.light_slider
    x_values: [0, 20, 40, 60, 80, 100]
    y_values: [0, 5, 15, 35, 65, 100]
    unit_of_measurement: "%"
    unique_id: "light_brightness_curve_01"
