name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Get version from tag
        id: tag_name
        run: |
          echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update manifest version
        run: |
          VERSION=${{ steps.tag_name.outputs.current_version }}
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/interpolation/manifest.json

      - name: Create zip file
        run: |
          cd custom_components/interpolation
          zip -r ../../interpolation.zip ./*

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./interpolation.zip
          asset_name: interpolation.zip
          tag: ${{ github.ref }}
          overwrite: true
